// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCziB6WM8PZF6NaxZKbvJ9t59CWDtpIT1Y',
    appId: '1:642011040906:web:fe68a90a67ee643b97b173',
    messagingSenderId: '642011040906',
    projectId: 'mobile-attendance-system-b8bd2',
    authDomain: 'mobile-attendance-system-b8bd2.firebaseapp.com',
    storageBucket: 'mobile-attendance-system-b8bd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTvHfHbfBLonpJG4N4nuc-3YiJ-TA655Y',
    appId: '1:642011040906:android:9eac56744d06582e97b173',
    messagingSenderId: '642011040906',
    projectId: 'mobile-attendance-system-b8bd2',
    storageBucket: 'mobile-attendance-system-b8bd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDHV0-wIgLuhWxzp7temDzm1lhKrWsbmI',
    appId: '1:642011040906:ios:893f00cfbe3baf4f97b173',
    messagingSenderId: '642011040906',
    projectId: 'mobile-attendance-system-b8bd2',
    storageBucket: 'mobile-attendance-system-b8bd2.firebasestorage.app',
    iosBundleId: 'com.example.attendNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDHV0-wIgLuhWxzp7temDzm1lhKrWsbmI',
    appId: '1:642011040906:ios:893f00cfbe3baf4f97b173',
    messagingSenderId: '642011040906',
    projectId: 'mobile-attendance-system-b8bd2',
    storageBucket: 'mobile-attendance-system-b8bd2.firebasestorage.app',
    iosBundleId: 'com.example.attendNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCziB6WM8PZF6NaxZKbvJ9t59CWDtpIT1Y',
    appId: '1:642011040906:web:8718abc35d0b985d97b173',
    messagingSenderId: '642011040906',
    projectId: 'mobile-attendance-system-b8bd2',
    authDomain: 'mobile-attendance-system-b8bd2.firebaseapp.com',
    storageBucket: 'mobile-attendance-system-b8bd2.firebasestorage.app',
  );
}
